name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      #  - name: Run tests
      #    run: npm test

      - name: Lint code
        run: npm run lint
